# Generated by Django 5.1.5 on 2025-03-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sold_by',
        ),
    ]
